In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.optim import SGD

In [2]:
x = torch.zeros((3,4), requires_grad=True)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], requires_grad=True)

In [4]:
a = (3*x).sum()
oa = SGD([x], momentum=0.0, lr=1.0)
oa

SGD (
Parameter Group 0
    dampening: 0
    lr: 1.0
    momentum: 0.0
    nesterov: False
    weight_decay: 0
)

In [6]:
oa.zero_grad()
a.backward()

In [7]:
x.grad

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [8]:
x._grad

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [10]:
print(x.grad[0][0])
x.grad[0][0] = 2.
print(x.grad)

tensor(3.)
tensor([[2., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [11]:
print(x._grad)

tensor([[2., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [12]:
x._grad[0][0] = 0.1
print(x._grad)

tensor([[0.1000, 3.0000, 3.0000, 3.0000],
        [3.0000, 3.0000, 3.0000, 3.0000],
        [3.0000, 3.0000, 3.0000, 3.0000]])
